### PR TITLE
Local storage routing

### PR DESCRIPTION
**Pull request by MikaelaNystrom**
Make LocalStorageRouting the latest base code by merging to dev

### CODE REVIEW

**Comment by Krezeb** [comment]
Kör på!

**Review by Kjellberg90 — APPROVED** [review]

**Review by Bergewing — APPROVED** [review]
Bra jobb!

**Review by Krezeb — APPROVED** [review]
Kör på.

**Review by Saru444 — APPROVED** [review]
ser bra ut

**Pull request merged**
